#!/bin/bash 
#Created by: Daniel Ferreira de Lima
#Last Release: 1.2
#Changelog: 1.2 - Sáb Mar  5 18:37 2015 Catch redirect loop
#           1.1 - Sáb Mar  5 15:19 2016 Added headers preventing block 
#           1.0 - Sex Mar  4 14:55 2016 First release
#Email: daniel.ferreira@adtsys.com.br 
#Description: url tracerouting with redirects
#VIM<3 

site=$1 
http_code=300 
n=0 
timeout=15
echo -n "Start tracing $1 "; 
echo '['$(host  $site|egrep -o "([0-9]{1,3}.){4}$")']' 
while [[ ${http_code} =~ ^3[0-9]{2}$ ]] ; do 

    #awfully necessary headers
    http_code=`curl -m $timeout \
        -H 'Accept-Language: en-US,en;q=0.8' \
        -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' \
        -H 'Referer: http://google.com/search?q=IT' --cookie key='20519d5b' \
        -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'  $site -w %{http_code} -o /dev/null -s `

    echo "[$n] - [$1] -- [$site] ... code $http_code" 

    #------------------------

    actualsite=$site
    site=`curl -m $timeout \
        -H 'Accept-Language: en-US,en;q=0.8' \
        -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' \
        -H 'Referer: http://google.com/search?q=IT' --cookie key='20519d5b' \
        -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36' \
        -Iv $site 2>&1 |tr -d '\r'| sed -rn 's/^[lL]oc(.*) (http.?:\/\/)?([.0-9A-Za-z=&%$#_-?/]+)$/\3/p'`

    if [[ "$actualsite" = "$site"  ]] ;then
        echo "redirect loop?"
        break
    fi

    if [[ $site =~ ^(\.|\/) ]]; then
        if [[ ${site:0:2} = "./" ]] ;then
            #./index -> site/foo/index
            site=$actualsite${site:2}
        else
            #/index -> site/index
            site=$actualsite${site:1}
        fi 
    fi
    let $((n++)) 
done 

